# Generated by Django 5.0.4 on 2026-06-22 15:54
from enum import unique

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    # SELECT * FROM shoe;
    # shoes = ShoeModel.objects.all()
    # print({s.brand for s in shoes})

    # SELECT DISTINCT brand FROM shoe;
    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    # for b in unique_brands:
    #     brand = UniqueBrandsModel(brand=b)
    #     brand.save()  # INSERT ONLY ONE ROW;

    unique_brands_to_create = [UniqueBrandsModel(brand=b) for b in unique_brands]
    UniqueBrandsModel.objects.bulk_create(unique_brands_to_create)  # INSERT multiple records at once


def reverse_create_unique_brands(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.all().delete()  # DELETE FROM unique_brands;


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        )
    ]
