# Generated by Django 5.0.4 on 2026-06-22 17:22

from django.db import migrations


def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')

    for i in ItemModel.objects.all():
        if i.price < 10:
            i.rarity = "Rare"
        elif i.price <= 20:
            i.rarity = "Very Rare"
        elif i.price <= 30:
            i.rarity = "Extremely Rare"
        else:
            i.rarity = "Mega Rare"

        i.save()


def reverse_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    default_value = ItemModel._meta.get_field('rarity').default

    for i in ItemModel.objects.all():
        i.rarity = default_value
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_rarity,
            reverse_code=reverse_rarity,
        )
    ]
