"""Create Chef model

Revision ID: e25dea804635
Revises: 3e1b33607346
Create Date: 2026-07-16 19:39:27.053454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25dea804635'
down_revision: Union[str, Sequence[str], None] = '3e1b33607346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'chef', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'chef_id')
    op.drop_table('chef')
    # ### end Alembic commands ###
